### ISSUE TITLE
Запуск клиента

### ISSUE THREAD

**Issue by jbmeerkat** [lenshq/lens_client#31]
Предлагаю [убрать запуск клиента из процесса конфигурации](https://github.com/lenshq/lens_client/blob/9d8b2d9ca7853a4b848830d774a176a635c02107/lib/lens.rb#L18). Это странно и неожиданно для пользователя. Если запускаемcя в Rails окружении, то можем привязаться [на процесс запуска Rails](http://guides.rubyonrails.org/configuring.html#highlighter_655683) ([пример из Airbrake](https://github.com/airbrake/airbrake/blob/25c7b5c756a13e95c8e267bcbe20c9906be0da1b/lib/airbrake/railtie.rb#L29)), иначе ручной запуск.

/cc @zzet @kgorin @JanaVPetrova

**Comment by kgorin** [comment]
Предложение хорошее
