### ISSUE TITLE
Снизить объем траффика от клиента к серверу

### ISSUE THREAD

**Issue by zzet** [lenshq/lens_client#5]
Данные из клиента отправляются в виде JSON без сжатия, что чревато большими затратами на сеть и время отправки данных.

- [x] Добавить сжатие данных при отправке данных на сервер (gzip, bzip2, [brotli](http://www.gstatic.com/b/brotlidocs/brotli-2015-09-22.pdf), ...)
- [x] Выбрать формат данных, который будет меньше весить (JSON, BSON, [Protobuf](https://github.com/google/protobuf), [Msgpack](http://msgpack.org/), ...)
- [x] Сделать бенчмарки на разных вариантах (формат/сжатие), для выбора самого оптимального

**Comment by inem** [comment]
Для protobuf я так понял [надо отдельно его самого ставить на системе](https://github.com/ruby-protobuf/protobuf/wiki/Installation#osx-install), что как бы повышает входной барьер для использования гема. Или нас это не пугает?

**Comment by inem** [comment]
```
Compressor              Original Compressed
Lens::Compression::Gzip 15922    1613      
Lens::Compression::Bson 15922    15927     
```
BSON чота странный. Или я чего-то не понимаю, или он нифига даже не пытается строки сжимать

**Comment by jbmeerkat** [comment]
> Для protobuf я так понял надо отдельно его самого ставить на системе, что как бы повышает входной барьер для использования гема. Или нас это не пугает?

@inem если это позволит существенно снизить передаваемый объем данных, то думаю, что не пугает.

/cc @zzet

**Comment by jbmeerkat** [comment]
> BSON чота странный.

@inem Вань, что-то я по запаре написал его туда не к месту, а Андрей так тикет и скопировал. BSON не поможет нам снизить объем траффика. Это скорее про скорость парсинга данных. В общем забей на него, это не про траффик)

**Comment by zzet** [comment]
@jbmeerkat @inem боюсь, что мы сейчас не можем заставить пользователя ставить что-то специфичное с гемом вместе. Сколько мы выиграем, если будет использоваться protobuf?

**Comment by zzet** [comment]
@inem на стороне сервера не нужно делать правки? Там же нужно будет разжимать данные?

**Comment by jbmeerkat** [comment]
> боюсь, что мы сейчас не можем заставить пользователя ставить что-то специфичное с гемом вместе. Сколько мы выиграем, если будет использоваться protobuf?

@zzet так я и говорю, что есть смысл если будет серьезный профит. Но вообще ты же сам считал, что при высокой нагрузке мы будет генерировать очень много траффика, так что не думаю, что у нас так уж много вариантов.

**Comment by zzet** [comment]
@jbmeerkat судя по цифрам, которые дал @inem - у нас сжатие получилось до x15. Весь вопрос только в том, даст ли такой же профит protobuf?

**Comment by jbmeerkat** [comment]
@zzet погоди, так это разные вещи. Мы можем выбрать более компактный формат данных и, в дополнение, использовать сжатие. Одно другое дополняет. Так что вопрос не в том даст ли protobuf такой же профит, а в том насколько он уменьшит объем данных в дополнение к сжатию.

**Comment by zzet** [comment]
@jbmeerkat а если protobuf при сжатии окажется не эффективнее, чем json - тогда он (protobuf) не нужен. Если даст еще больше экономии траффика - то это уже повод задуматься как заставить пользователя поставить protobuf...

**Comment by jbmeerkat** [comment]
@zzet ![captain_obvious](https://cloud.githubusercontent.com/assets/847534/10577607/533e5082-7675-11e5-8a71-a44637a8cf03.jpg)

**Comment by inem** [comment]
>Сколько мы выиграем, если будет использоваться protobuf?

не мерил еще

>на стороне сервера не нужно делать правки? Там же нужно будет разжимать данные?

нужно, только наверное сначала надо что-то выбрать на клиенте

**Comment by inem** [comment]
О, а дайте мне кто-нибудь пример данных, которые мы передаем?
А то я сейчас кусок лога просто сжимаю, но там ведь еще что-то кроме этого мы собираемся гонять

cc @zzet @jbmeerkat

**Comment by zzet** [comment]
@inem https://github.com/lenshq/lens_server/blob/master/spec/factories/raw_event.rb

**Comment by inem** [comment]
Update:
```
Compressor                  Original Compressed Rate
Lens::Compression::Gzip     2823     764        27% 
Lens::Compression::Bson     2823     1831       65% 
Lens::Compression::BsonGzip 2823     818        29% 
```

А мы собираемся по одному кусочку отправлять каждый раз?  Gzip ведь тем эффективнее, чем большее кол-во однотипных данных мы оправляем.

**Comment by zzet** [comment]
@inem пока что да, по на каждый реквест по запросу. Насчет батчей - нужно хорошенько подумать, как сделать, чтобы не терять данные (и чтобы не распухать в памяти).

**Comment by zzet** [comment]
@inem сделаешь замер для protobuf? чтобы можно было решение принять?

p.s. ты только на небольшом json проверял? А что будет, если JSON будет ~200-500 кб?

**Comment by inem** [comment]
protobuf - курю. 
JSON - накидайте в меня разных данных - на всех потестю.

**Comment by kgorin** [comment]
https://dl.dropboxusercontent.com/u/7460606/data.json

**Comment by inem** [comment]
```
Compressor                  Original Compressed Rate Data                                                               
Lens::Compression::Gzip     2823     764        27%  {\n  "data":{\n    "action":"index",\n    "controller":"Admin::R...
Lens::Compression::Bson     2823     1831       65%  {\n  "data":{\n    "action":"index",\n    "controller":"Admin::R...
Lens::Compression::BsonGzip 2823     818        29%  {\n  "data":{\n    "action":"index",\n    "controller":"Admin::R...
Lens::Compression::Gzip     40690    4878       12%  {"data":{"action":"index","controller":"HomePagesController",...   
Lens::Compression::Bson     40690    37237      92%  {"data":{"action":"index","controller":"HomePagesController",...   
Lens::Compression::BsonGzip 40690    6014       15%  {"data":{"action":"index","controller":"HomePagesController",...   

```

**Comment by inem** [comment]
Получил кое-что с Protobuf. Для этого упростил датасет до такого: https://gist.github.com/inem/f46f76006bf4169f80f8

В итоге вот такие цифры
```
Compressor                      Original Compressed Rate 
Lens::Compression::Gzip         43652    4152       10%  
Lens::Compression::Bson         43652    31810      73%  
Lens::Compression::BsonGzip     43652    4857       11%  
Lens::Compression::Protobuf     43652    23464      54%  
Lens::Compression::ProtobufGzip 43652    2846       7%   
```

В общем да, Protobuf+Gzip похоже что эффективнее чем JSON+Gzip, но надо понимать что это не просто `data.to_protobuf`. Это надо все описать в классах [типа такого](https://github.com/lenshq/lens_client/blob/124c711745a46725964e7d0c8fb53ad634bbcc27/lib/lens/compression.rb#L27-L43). 

Подозреваю что если целиком и на клиенте и на сервере перейти на Protobuf, это будет даже удобнее чем с JSON возиться. Если же есть идеи поддерживать несколько вариантов пересылки данных, то надо будет делать что-то типа слоя адаптеров с обоих сторон.

Ну и сейчас это с небольшой потерей данных работает:
```ruby
[3] pry(Lens::Compression::ProtobufGzip)> Batch.decode(GzipUtil.gunzip(aaa)).records.first
=> <Lens::Compression::ProtobufGzip::Record etype: "sql.active_record", eduration: 2.5661420822143555, etype: "sql.active_record", estart: 1437835520.0, efinish: 1437835520.0, sql: "            SELECT a.attname, format_type(a.atttypid, a.atttypmod),\n                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod\n              FROM pg_attribute a LEFT JOIN pg_attrdef d\n                ON a.attrelid = d.adrelid AND a.attnum = d.adnum\n             WHERE a.attrelid = '\"users\"'::regclass\n               AND a.attnum > 0 AND NOT a.attisdropped\n             ORDER BY a.attnum\n", name: "SCHEMA", connection_id: 27250300>
```
`estart` и `efinish` потеряли все после точки. Это наверное можно вылечить, задав правильный тип. Какойнть float64 или DateTime, но я до датих деталей с Protobuf еще не дошел.

**Comment by zzet** [comment]
@inem потеря данных - это очень хреново...

@jbmeerkat думаю, что сейчас можно остановиться на варианте Gzip(JSON).
Поддержка проще, проблем пока не поймаем. Мы не можем терять данные из-за того, что что-то не описали. Мы про потерянные данные так в итоге и не узнаем :(

Что скажешь?

**Comment by inem** [comment]
Про потери - я ж говорю, это преодолимо почти наверняка.

**Comment by inem** [comment]
Проапдэйтил коммент чтоб было понятнее что потерялось

**Comment by zzet** [comment]
@inem мне вот тут https://github.com/lenshq/lens_client/blob/master/lib/lens/trace.rb#L13-L20 гибкость на начальном этапе терять не хочется. Если мы сейчас жестко ограничим структуру данных - про какие-то специфические кейсы не узнаем.

**Comment by inem** [comment]
С гибкостью у protobuf вроде больменее. Можно будет [тут](https://github.com/lenshq/lens_client/blob/124c711745a46725964e7d0c8fb53ad634bbcc27/lib/lens/compression.rb#L33-L34) другие циферки прописать, и это будет работать как версионность API. Вроде бы. Деталей не знаю.

Но generally я тоже склоняюсь к тому что Protobuf - это типа такой выбор на всю жизнь, и на начальном этапе такое решение принимать не оч.

**Comment by zzet** [comment]
@inem в точку. Мне сейчас страшно на него завязываться, тем более, когда нужно больше гибкости.

**Comment by jbmeerkat** [comment]
@zzet @inem давайте пока останемся на json и будем по мере появления проблем использовать другие варианты. Бенчмарки и прототип кода у нас уже есть если что)

p.s. было бы еще очень интересно как-нибудь потом посмотреть msgpack в качестве формата данных и другие алгоритмы сжатия

**Comment by JanaVPetrova** [comment]
@zzet @inem @jbmeerkat 
может, немного не в тему и это не войдет в MVP, но есть идея сделать возможность выбора стратегии сжатия. и доку со всеми замерами и возможными последствиями приложить.

это так, идея на подумать в будущем =)

**Comment by zzet** [comment]
@JanaVPetrova хз, не вижу особой надобности в поддержке N вариантов сжатия
